FROM golang:1.26-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /bin/server ./cmd/server
RUN CGO_ENABLED=0 go build -o /bin/hlsupload ./cmd/hlsupload

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=build /bin/server /usr/local/bin/server
COPY --from=build /bin/hlsupload /usr/local/bin/hlsupload
USER nobody
ENTRYPOINT ["server"]
