// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannelForUser = `-- name: CreateChannelForUser :one
INSERT INTO channels (user_id)
VALUES ($1)
RETURNING id, user_id, title, category, thumbnail_url, avatar_url, is_live, created_at
`

type CreateChannelForUserRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Title        string
	Category     string
	ThumbnailUrl string
	AvatarUrl    string
	IsLive       bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateChannelForUser(ctx context.Context, userID pgtype.UUID) (CreateChannelForUserRow, error) {
	row := q.db.QueryRow(ctx, createChannelForUser, userID)
	var i CreateChannelForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.AvatarUrl,
		&i.IsLive,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, username, created_at
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash pgtype.Text
}

type CreateUserRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getChannelByUserID = `-- name: GetChannelByUserID :one
SELECT id, user_id, title, category, thumbnail_url, stream_key_hash, is_live, created_at, stream_key_preview, avatar_url FROM channels WHERE user_id = $1
`

func (q *Queries) GetChannelByUserID(ctx context.Context, userID pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByUserID, userID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.StreamKeyHash,
		&i.IsLive,
		&i.CreatedAt,
		&i.StreamKeyPreview,
		&i.AvatarUrl,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.email, u.username, s.expires_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionUserRow struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, created_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
