// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChannelDashboardByUserID = `-- name: GetChannelDashboardByUserID :one
SELECT
    c.id,
    c.user_id,
    c.title,
    c.category,
    c.thumbnail_url,
    c.stream_key_hash,
    c.is_live,
    c.created_at,
    u.username
FROM channels c
JOIN users u ON u.id = c.user_id
WHERE c.user_id = $1
`

type GetChannelDashboardByUserIDRow struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	Title         string
	Category      string
	ThumbnailUrl  string
	StreamKeyHash pgtype.Text
	IsLive        bool
	CreatedAt     pgtype.Timestamptz
	Username      string
}

func (q *Queries) GetChannelDashboardByUserID(ctx context.Context, userID pgtype.UUID) (GetChannelDashboardByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getChannelDashboardByUserID, userID)
	var i GetChannelDashboardByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.StreamKeyHash,
		&i.IsLive,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const updateChannelMetadata = `-- name: UpdateChannelMetadata :one
UPDATE channels
SET title = $2, category = $3
WHERE user_id = $1
RETURNING id, user_id, title, category, thumbnail_url, stream_key_hash, is_live, created_at
`

type UpdateChannelMetadataParams struct {
	UserID   pgtype.UUID
	Title    string
	Category string
}

func (q *Queries) UpdateChannelMetadata(ctx context.Context, arg UpdateChannelMetadataParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannelMetadata, arg.UserID, arg.Title, arg.Category)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.StreamKeyHash,
		&i.IsLive,
		&i.CreatedAt,
	)
	return i, err
}

const updateChannelThumbnail = `-- name: UpdateChannelThumbnail :one
UPDATE channels
SET thumbnail_url = $2
WHERE user_id = $1
RETURNING id, user_id, title, category, thumbnail_url, stream_key_hash, is_live, created_at
`

type UpdateChannelThumbnailParams struct {
	UserID       pgtype.UUID
	ThumbnailUrl string
}

func (q *Queries) UpdateChannelThumbnail(ctx context.Context, arg UpdateChannelThumbnailParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannelThumbnail, arg.UserID, arg.ThumbnailUrl)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.StreamKeyHash,
		&i.IsLive,
		&i.CreatedAt,
	)
	return i, err
}
