// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllLiveChannels = `-- name: GetAllLiveChannels :many
SELECT id, user_id, title, category, thumbnail_url, stream_key_hash, stream_key_preview, is_live, created_at
FROM channels
WHERE is_live = true
`

type GetAllLiveChannelsRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Title            string
	Category         string
	ThumbnailUrl     string
	StreamKeyHash    pgtype.Text
	StreamKeyPreview string
	IsLive           bool
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetAllLiveChannels(ctx context.Context) ([]GetAllLiveChannelsRow, error) {
	rows, err := q.db.Query(ctx, getAllLiveChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLiveChannelsRow
	for rows.Next() {
		var i GetAllLiveChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Category,
			&i.ThumbnailUrl,
			&i.StreamKeyHash,
			&i.StreamKeyPreview,
			&i.IsLive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelByStreamKeyHash = `-- name: GetChannelByStreamKeyHash :one
SELECT id, user_id, title, category, thumbnail_url, stream_key_hash, stream_key_preview, is_live, created_at
FROM channels
WHERE stream_key_hash = $1
`

type GetChannelByStreamKeyHashRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Title            string
	Category         string
	ThumbnailUrl     string
	StreamKeyHash    pgtype.Text
	StreamKeyPreview string
	IsLive           bool
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetChannelByStreamKeyHash(ctx context.Context, streamKeyHash pgtype.Text) (GetChannelByStreamKeyHashRow, error) {
	row := q.db.QueryRow(ctx, getChannelByStreamKeyHash, streamKeyHash)
	var i GetChannelByStreamKeyHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.StreamKeyHash,
		&i.StreamKeyPreview,
		&i.IsLive,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelDashboardByUserID = `-- name: GetChannelDashboardByUserID :one
SELECT
    c.id,
    c.user_id,
    c.title,
    c.category,
    c.thumbnail_url,
    c.stream_key_hash,
    c.stream_key_preview,
    c.is_live,
    c.created_at,
    u.username
FROM channels c
JOIN users u ON u.id = c.user_id
WHERE c.user_id = $1
`

type GetChannelDashboardByUserIDRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Title            string
	Category         string
	ThumbnailUrl     string
	StreamKeyHash    pgtype.Text
	StreamKeyPreview string
	IsLive           bool
	CreatedAt        pgtype.Timestamptz
	Username         string
}

func (q *Queries) GetChannelDashboardByUserID(ctx context.Context, userID pgtype.UUID) (GetChannelDashboardByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getChannelDashboardByUserID, userID)
	var i GetChannelDashboardByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.StreamKeyHash,
		&i.StreamKeyPreview,
		&i.IsLive,
		&i.CreatedAt,
		&i.Username,
	)
	return i, err
}

const getChannelUsernameByStreamKeyHash = `-- name: GetChannelUsernameByStreamKeyHash :one
SELECT u.username
FROM channels c
JOIN users u ON u.id = c.user_id
WHERE c.stream_key_hash = $1
`

func (q *Queries) GetChannelUsernameByStreamKeyHash(ctx context.Context, streamKeyHash pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getChannelUsernameByStreamKeyHash, streamKeyHash)
	var username string
	err := row.Scan(&username)
	return username, err
}

const getPublicChannelByUsername = `-- name: GetPublicChannelByUsername :one
SELECT c.id, c.user_id, u.username, c.title, c.category, c.thumbnail_url, c.is_live, c.created_at
FROM channels c
JOIN users u ON u.id = c.user_id
WHERE u.username = $1
`

type GetPublicChannelByUsernameRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Username     string
	Title        string
	Category     string
	ThumbnailUrl string
	IsLive       bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetPublicChannelByUsername(ctx context.Context, username string) (GetPublicChannelByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getPublicChannelByUsername, username)
	var i GetPublicChannelByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.IsLive,
		&i.CreatedAt,
	)
	return i, err
}

const listLiveChannels = `-- name: ListLiveChannels :many
SELECT c.id, c.user_id, u.username, c.title, c.category, c.thumbnail_url, c.is_live, c.created_at
FROM channels c
JOIN users u ON u.id = c.user_id
WHERE c.is_live = true
ORDER BY c.created_at DESC
`

type ListLiveChannelsRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Username     string
	Title        string
	Category     string
	ThumbnailUrl string
	IsLive       bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListLiveChannels(ctx context.Context) ([]ListLiveChannelsRow, error) {
	rows, err := q.db.Query(ctx, listLiveChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveChannelsRow
	for rows.Next() {
		var i ListLiveChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Title,
			&i.Category,
			&i.ThumbnailUrl,
			&i.IsLive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveChannelsByCategory = `-- name: ListLiveChannelsByCategory :many
SELECT c.id, c.user_id, u.username, c.title, c.category, c.thumbnail_url, c.is_live, c.created_at
FROM channels c
JOIN users u ON u.id = c.user_id
WHERE c.is_live = true AND c.category = $1
ORDER BY c.created_at DESC
`

type ListLiveChannelsByCategoryRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Username     string
	Title        string
	Category     string
	ThumbnailUrl string
	IsLive       bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListLiveChannelsByCategory(ctx context.Context, category string) ([]ListLiveChannelsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listLiveChannelsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveChannelsByCategoryRow
	for rows.Next() {
		var i ListLiveChannelsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Title,
			&i.Category,
			&i.ThumbnailUrl,
			&i.IsLive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelLive = `-- name: SetChannelLive :exec
UPDATE channels
SET is_live = $2
WHERE id = $1
`

type SetChannelLiveParams struct {
	ID     pgtype.UUID
	IsLive bool
}

func (q *Queries) SetChannelLive(ctx context.Context, arg SetChannelLiveParams) error {
	_, err := q.db.Exec(ctx, setChannelLive, arg.ID, arg.IsLive)
	return err
}

const updateChannelMetadata = `-- name: UpdateChannelMetadata :one
UPDATE channels
SET title = $2, category = $3
WHERE user_id = $1
RETURNING id, user_id, title, category, thumbnail_url, stream_key_hash, stream_key_preview, is_live, created_at
`

type UpdateChannelMetadataParams struct {
	UserID   pgtype.UUID
	Title    string
	Category string
}

type UpdateChannelMetadataRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Title            string
	Category         string
	ThumbnailUrl     string
	StreamKeyHash    pgtype.Text
	StreamKeyPreview string
	IsLive           bool
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateChannelMetadata(ctx context.Context, arg UpdateChannelMetadataParams) (UpdateChannelMetadataRow, error) {
	row := q.db.QueryRow(ctx, updateChannelMetadata, arg.UserID, arg.Title, arg.Category)
	var i UpdateChannelMetadataRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.StreamKeyHash,
		&i.StreamKeyPreview,
		&i.IsLive,
		&i.CreatedAt,
	)
	return i, err
}

const updateChannelStreamKey = `-- name: UpdateChannelStreamKey :one
UPDATE channels
SET stream_key_hash = $2, stream_key_preview = $3
WHERE user_id = $1
RETURNING id, user_id, title, category, thumbnail_url, stream_key_hash, stream_key_preview, is_live, created_at
`

type UpdateChannelStreamKeyParams struct {
	UserID           pgtype.UUID
	StreamKeyHash    pgtype.Text
	StreamKeyPreview string
}

type UpdateChannelStreamKeyRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Title            string
	Category         string
	ThumbnailUrl     string
	StreamKeyHash    pgtype.Text
	StreamKeyPreview string
	IsLive           bool
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateChannelStreamKey(ctx context.Context, arg UpdateChannelStreamKeyParams) (UpdateChannelStreamKeyRow, error) {
	row := q.db.QueryRow(ctx, updateChannelStreamKey, arg.UserID, arg.StreamKeyHash, arg.StreamKeyPreview)
	var i UpdateChannelStreamKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.StreamKeyHash,
		&i.StreamKeyPreview,
		&i.IsLive,
		&i.CreatedAt,
	)
	return i, err
}

const updateChannelThumbnail = `-- name: UpdateChannelThumbnail :one
UPDATE channels
SET thumbnail_url = $2
WHERE user_id = $1
RETURNING id, user_id, title, category, thumbnail_url, stream_key_hash, stream_key_preview, is_live, created_at
`

type UpdateChannelThumbnailParams struct {
	UserID       pgtype.UUID
	ThumbnailUrl string
}

type UpdateChannelThumbnailRow struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	Title            string
	Category         string
	ThumbnailUrl     string
	StreamKeyHash    pgtype.Text
	StreamKeyPreview string
	IsLive           bool
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateChannelThumbnail(ctx context.Context, arg UpdateChannelThumbnailParams) (UpdateChannelThumbnailRow, error) {
	row := q.db.QueryRow(ctx, updateChannelThumbnail, arg.UserID, arg.ThumbnailUrl)
	var i UpdateChannelThumbnailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Category,
		&i.ThumbnailUrl,
		&i.StreamKeyHash,
		&i.StreamKeyPreview,
		&i.IsLive,
		&i.CreatedAt,
	)
	return i, err
}
