// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follow.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const followChannel = `-- name: FollowChannel :exec
INSERT INTO follows (follower_user_id, channel_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowChannelParams struct {
	FollowerUserID pgtype.UUID
	ChannelID      pgtype.UUID
}

func (q *Queries) FollowChannel(ctx context.Context, arg FollowChannelParams) error {
	_, err := q.db.Exec(ctx, followChannel, arg.FollowerUserID, arg.ChannelID)
	return err
}

const getFollowerCount = `-- name: GetFollowerCount :one
SELECT COUNT(*) FROM follows WHERE channel_id = $1
`

func (q *Queries) GetFollowerCount(ctx context.Context, channelID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getFollowerCount, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM follows WHERE follower_user_id = $1 AND channel_id = $2
)
`

type IsFollowingParams struct {
	FollowerUserID pgtype.UUID
	ChannelID      pgtype.UUID
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerUserID, arg.ChannelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unfollowChannel = `-- name: UnfollowChannel :exec
DELETE FROM follows
WHERE follower_user_id = $1 AND channel_id = $2
`

type UnfollowChannelParams struct {
	FollowerUserID pgtype.UUID
	ChannelID      pgtype.UUID
}

func (q *Queries) UnfollowChannel(ctx context.Context, arg UnfollowChannelParams) error {
	_, err := q.db.Exec(ctx, unfollowChannel, arg.FollowerUserID, arg.ChannelID)
	return err
}
