// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: google.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO identities (provider, subject, user_id)
VALUES ($1, $2, $3)
`

type CreateIdentityParams struct {
	Provider string
	Subject  string
	UserID   pgtype.UUID
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity, arg.Provider, arg.Subject, arg.UserID)
	return err
}

const getIdentity = `-- name: GetIdentity :one
SELECT provider, subject, user_id, created_at FROM identities WHERE provider = $1 AND subject = $2
`

type GetIdentityParams struct {
	Provider string
	Subject  string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Provider, arg.Subject)
	var i Identity
	err := row.Scan(
		&i.Provider,
		&i.Subject,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
